services:
  load-balancer:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-network
    depends_on:
      - ws-1
      - ws-2

  ws-1:
    build: .
    profiles: ["server", "DB"]
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
    ports:
      - 8081:3000
    # The commented out section below is an example of how to define a PostgreSQL
    # database that your application can use. `depends_on` tells Docker Compose to
    # start the database before your application.
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network

  ws-2:
    build: .
    profiles: ["server", "DB"]
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
    ports:
      - 8082:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network

  db:
    image: postgres:14-alpine
    profiles: ["DB"]
    restart: unless-stopped
    user: postgres
    secrets:
      - db-password
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:

secrets:
  db-password:
    file: db/password.txt

networks:
  backend-network:
    driver: bridge
