apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: eso-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  # data:
  #   - secretKey: secret-key-to-be-managed
  #     remoteRef:
  #       key: provider-key
  #       version: provider-key-version
  #       property: provider-key-property
  dataFrom:
    - extract:
        key: DB_CREDENTIALS
