---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cm
  namespace: eso-ns
  labels:
    type: db
data:
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: eso-ns
  labels:
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: db-deploy-pod
      namespace: eso-ns
      labels:
        type: db
    spec:
      containers:
        - name: db-deploy-pod
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
      nodeSelector:
        type: db

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: eso-ns
  labels:
    type: db
spec:
  type: ClusterIP
  selector:
    type: db
  ports:
    - port: 5432
      targetPort: 5432
