apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: student-api-ns
  labels:
    type: db
spec:
  containers:
    - name: db-pod
      image: postgres:14-alpine
      imagePullPolicy: IfNotPresent
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 5432
  nodeSelector:
    type: db
