apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: student-api-ns
  labels:
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: db-deploy-pod
      namespace: student-api-ns
      labels:
        type: db
    spec:
      containers:
        - name: db-deploy-pod
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
      nodeSelector:
        type: db
