---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm
  namespace: eso-ns
  labels:
    type: app
data:
  NODE_ENV: "development"
  DB_USER: "postgres"
  DB_HOST: "db-service"
  DB_PORT: "5432"
  DB_DATABASE: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: eso-ns
  labels:
    type: app
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: app-deploy-pod
      namespace: eso-ns
      labels:
        type: app
    spec:
      containers:
        - name: app-deploy-pod
          image: docker.io/awsclouddev/sre-bootcamp-web-server:v3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: NODE_ENV

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_PORT

            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_DATABASE

          ports:
            - containerPort: 3000
      initContainers:
        - name: init-app-cont
          image: docker.io/awsclouddev/sre-bootcamp-web-server:milestone-5
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: NODE_ENV

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_PASSWORD

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_PORT

            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: DB_DATABASE
          command: ["sh", "-c", "npx knex migrate:latest"]
      nodeSelector:
        type: app

---
apiVersion: v1
kind: Service
metadata:
  name: ws-service
  namespace: eso-ns
  labels:
    type: app
spec:
  type: NodePort
  selector:
    type: app
  ports:
    - port: 8000
      targetPort: 3000
      nodePort: 30002
