apiVersion: v1
kind: Namespace
metadata:
  name: student-api-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: student-api-ns
  labels:
    type: application
spec:
  replicas: 2
  selector:
    matchLabels:
      type: application
  template:
    metadata:
      labels:
        type: application
    spec:
      containers:
        - name: ws
          image: docker.io/awsclouddev/sre-bootcamp-web-server:milestone-5
          env:
            - name: NODE_ENV
              value: "development"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "postgres"
          ports:
            - containerPort: 3000
