apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: student-api-ns
  labels:
    type: app
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: app-deploy-pod
      namespace: student-api-ns
      labels:
        type: app
    spec:
      containers:
        - name: app-deploy-pod
          image: docker.io/awsclouddev/sre-bootcamp-web-server:v3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "development"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_HOST
              value: db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "postgres"
          ports:
            - containerPort: 3000
      nodeSelector:
        type: app
